type User {
  authSub: String!
  id: ID
  isDriver: Boolean!
  username: String!
  friends: [ID]
  routes: [Route] @relation
}

type Route {
  user: User
  name: String
  startLocation: String!
  startTime: Time!
  endLocation: String!
  startRadius: String
  endRadius: String
  timeDeviation: Time
}
