type Location @embedded {
  lat: Number!
  lng: Number!
  description: String!
}

type User {
  authSub: String!
  isDriver: Boolean
  authName: String!
  sex: String
  wantSameSex: Boolean
  friends: [ID]
  routes: [Route!] @relation
}

type Route {
  user: User!
  nickName: String!
  startLocation: Location!
  startTime: Time!
  endLocation: Location!
  startRadius: Number!
  endRadius: Number!
  timeDeviation: Time!
  returnRoute: Route!
}

type Query {
  getUserByAuthSub(authSub: String!): User
}
